language: node_js

node_js: "6"

before_install:
  - gem install sass

install:
  - npm install

script:
  - npm run img
  - npm run build
  - npm run sitemap

after_success:
  - npm run deploy-ftp

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules
