language: node_js

node_js: "6"

before_install:
  - gem install sass

install:
  - npm install

script:
  - npm run img
  - npm run build

after_success:
  - npm run deploy-ftp

branches:
  only:
  - master
